### ISSUE TITLE
Error during evaluate 

### ISSUE THREAD

**Issue by ZhengyiLuo** [phanideepgampa/stacked-capsule-networks#6]
Code crashes at line 49 in main.py

prev_labels[max_act>prev_max] = target[max_ex]

due to size mismatch. Any idea why? As a blind try I used:
prev_labels[max_act>prev_max] = target[max_ex][max_act>prev_max]
but then the model does not learn at all. Might need to take a deeper look, but would love to have something running. 

Thanks for the implementation though!

**Comment by alighofrani95** [comment]
exactly the same issue...

prev_labels[max_act>prev_max]= target[max_ex]
RuntimeError: shape mismatch: value tensor of shape [24] cannot be broadcast to indexing result of shape [11]

Could you please explain how to fix it? 

thanks

**Comment by AlanSky815** [comment]
Excuse me,
The same upper questions, could you please give  us some way to fix them, thank you。

**Comment by phanideepgampa** [comment]
Thank you for pointing out the errors, I have pushed the updated code. Was busy on other commitments.

The first loop basically assigns a class label for each capsule. Class labels for capsules are determined based on the maximum activation value a capsule achieves on an example in the whole dataset.

Please look at the updated code!

**Comment by ZhengyiLuo** [comment]
> Thank you for pointing out the errors, I have pushed the updated code. Was busy on other commitments.
> 
> The first loop basically assigns a class label for each capsule. Class labels for capsules are determined based on the maximum activation value a capsule achieves on an example in the whole dataset.
> 
> Please look at the updated code!

Thanks a lot for the update! The code runs smoothly now. 

However, the accuracy stays at 0 for all my runs, which I am trying to figure out why. Were you able to reproduce the result from the paper on your end?

**Comment by zyxforever** [comment]
> exactly the same issue...
> 
> prev_labels[max_act>prev_max]= target[max_ex]
> RuntimeError: shape mismatch: value tensor of shape [24] cannot be broadcast to indexing result of shape [11]
> 
> Could you please explain how to fix it?
> 
> thanks

I still have the same problem,could you tell me how to fix it?

**Comment by phanideepgampa** [comment]
Can you pull the latest code? as it is fixed in the new code.
